description: dante_rx_to_dante_tx
devices:
  samplerate: 48000
  chunksize: 1024
  capture_samplerate: 48000
  enable_rate_adjust: true
  capture:
    type: Alsa
    channels: 2
    device: inferno_rx2
    format: S32_LE
  playback:
    type: Alsa
    channels: 2
    device: inferno_tx2
    format: S32_LE
filters: {}
mixers:
  Mixer 1:
    channels:
      in: 2
      out: 2
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- type: Mixer
  name: Mixer 1
processors: {}
